name: Run ansible module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install
        pipenv run ansible-galaxy collection install ansible.netcommon:4.1.0
    - name: Lint with flake8
      run: |
        export ANSIBLE_CONFIG=./ansible.cfg
        pipenv run ansible -i inventory unicolet -m unicolet_ping
